name       : haskell-logict
version    : 0.7.0.2
release    : 3
source     :
    - https://hackage.haskell.org/package/logict-0.7.0.2/logict-0.7.0.2.tar.gz : ccc198a05563a4d8fc145ecde8b43a83599b3bcb032d2614a8e852f0ba6ecff5
license    : BSD-3-Clause
component  : programming.haskell
summary    : A continuation-based, backtracking, logic programming monad.
description: |
    A continuation-based, backtracking, logic programming monad.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
