name       : haskell-logict
version    : 0.6.0.2
release    : 2
source     :
    - http://hackage.haskell.org/package/logict-0.6.0.2/logict-0.6.0.2.tar.gz : 1182b68e8d00279460c7fb9b8284bf129805c07754c678b2a8de5a6d768e161e
license    : BSD-3-Clause
component  : programming.haskell
summary    : A continuation-based, backtracking, logic programming monad.
description: |
    A continuation-based, backtracking, logic programming monad.
builddeps  :
    - haskell-cabal-install
    - haskell-mtl
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
